apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworld-service
  name: helloworld-service
  namespace: prod
spec:
  type: LoadBalancer
  selector:
    app: helloworld
  ports:
  - name: helloworldport
    port: 80
    protocol: TCP
    targetPort: 8080




